package net.kdt.pojavlaunch.modloaders;

import android.content.Context;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.kdt.mcgui.ProgressLayout;

import net.kdt.pojavlaunch.R;
import net.kdt.pojavlaunch.Tools;
import net.kdt.pojavlaunch.progresskeeper.ProgressKeeper;
import net.kdt.pojavlaunch.utils.DownloadUtils;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Validates the artifacts generated by modern Forge installers.
 *
 * These files have no download URL in the Minecraft version JSON because Forge
 * creates them locally with its processors. A zero exit code alone is therefore
 * insufficient proof that Forge was installed correctly.
 */
public final class ForgeInstallationValidator {
    private static final String FORGE_CLIENT_TARGET = "forgeclient";

    private ForgeInstallationValidator() {
    }

    public static Status inspect(File minecraftDirectory, String versionId) throws IOException {
        File versionJson = new File(minecraftDirectory,
                "versions/" + versionId + "/" + versionId + ".json");
        if (!versionJson.isFile()) {
            return Status.notForge();
        }
        return inspectJson(minecraftDirectory, JsonParser.parseString(Tools.read(versionJson)).getAsJsonObject());
    }

    static Status inspectJson(File minecraftDirectory, JsonObject versionJson) {
        if (!containsMinecraftForgeLibrary(versionJson) || containsNeoForgeLibrary(versionJson)) {
            return Status.notForge();
        }
        JsonObject arguments = object(versionJson, "arguments");
        JsonArray gameArguments = arguments == null ? null : array(arguments, "game");
        if (gameArguments == null) {
            return Status.notForge();
        }

        List<String> values = flattenStringArguments(gameArguments);
        String launchTarget = valueAfter(values, "--launchTarget");
        if (launchTarget == null || !launchTarget.toLowerCase().contains(FORGE_CLIENT_TARGET)) {
            return Status.notForge();
        }

        String minecraftVersion = valueAfter(values, "--fml.mcVersion");
        String forgeVersion = valueAfter(values, "--fml.forgeVersion");
        String mcpVersion = valueAfter(values, "--fml.mcpVersion");
        if (!valid(minecraftVersion) || !valid(forgeVersion) || !valid(mcpVersion)) {
            return new Status(true, false, null,
                    Collections.singletonList("Forge metadata is incomplete"));
        }

        String minecraftProcessorVersion = minecraftVersion + "-" + mcpVersion;
        String forgeCoordinate = minecraftVersion + "-" + forgeVersion;
        List<File> expectedFiles = new ArrayList<>(3);
        expectedFiles.add(new File(minecraftDirectory,
                "libraries/net/minecraft/client/" + minecraftProcessorVersion
                        + "/client-" + minecraftProcessorVersion + "-srg.jar"));
        expectedFiles.add(new File(minecraftDirectory,
                "libraries/net/minecraft/client/" + minecraftProcessorVersion
                        + "/client-" + minecraftProcessorVersion + "-extra.jar"));
        expectedFiles.add(new File(minecraftDirectory,
                "libraries/net/minecraftforge/forge/" + forgeCoordinate
                        + "/forge-" + forgeCoordinate + "-client.jar"));

        List<String> missing = new ArrayList<>();
        for (File expectedFile : expectedFiles) {
            if (!expectedFile.isFile() || expectedFile.length() == 0) {
                missing.add(expectedFile.getAbsolutePath());
            }
        }
        return new Status(true, missing.isEmpty(), forgeCoordinate,
                Collections.unmodifiableList(missing));
    }

    private static boolean containsMinecraftForgeLibrary(JsonObject versionJson) {
        JsonArray libraries = array(versionJson, "libraries");
        if (libraries == null) {
            return false;
        }
        for (JsonElement element : libraries) {
            if (!element.isJsonObject()) {
                continue;
            }
            JsonElement name = element.getAsJsonObject().get("name");
            if (name != null && name.isJsonPrimitive()
                    && name.getAsString().startsWith("net.minecraftforge:forge:")) {
                return true;
            }
        }
        return false;
    }

    private static boolean containsNeoForgeLibrary(JsonObject versionJson) {
        JsonArray libraries = array(versionJson, "libraries");
        if (libraries == null) {
            return false;
        }
        for (JsonElement element : libraries) {
            if (!element.isJsonObject()) {
                continue;
            }
            JsonElement name = element.getAsJsonObject().get("name");
            if (name != null && name.isJsonPrimitive()
                    && name.getAsString().startsWith("net.neoforged:")) {
                return true;
            }
        }
        return false;
    }

    public static void assertComplete(File minecraftDirectory, String versionId) throws IOException {
        Status status = inspect(minecraftDirectory, versionId);
        if (status.forge && !status.complete) {
            throw status.asException();
        }
    }

    public static void repairIfNeeded(Context context, String versionId) throws IOException {
        Status before = inspect(new File(Tools.DIR_GAME_NEW), versionId);
        if (!before.forge || before.complete) {
            return;
        }
        if (!valid(before.forgeCoordinate)) {
            throw before.asException();
        }

        ProgressKeeper.submitProgress(ProgressLayout.DOWNLOAD_MINECRAFT, 96,
                R.string.modloader_installing);
        File installer = new File(Tools.DIR_CACHE,
                "forge-" + before.forgeCoordinate + "-installer.jar");
        DownloadUtils.downloadFile(ForgeUtils.getInstallerUrl(before.forgeCoordinate), installer);
        ForgeInstaller.install(context.getApplicationContext(), installer, false);
        assertComplete(new File(Tools.DIR_GAME_NEW), versionId);
    }

    private static List<String> flattenStringArguments(JsonArray arguments) {
        List<String> values = new ArrayList<>();
        for (JsonElement argument : arguments) {
            if (argument.isJsonPrimitive() && argument.getAsJsonPrimitive().isString()) {
                values.add(argument.getAsString());
            }
        }
        return values;
    }

    private static String valueAfter(List<String> arguments, String key) {
        for (int i = 0; i + 1 < arguments.size(); i++) {
            if (key.equals(arguments.get(i))) {
                return arguments.get(i + 1);
            }
        }
        return null;
    }

    private static JsonObject object(JsonObject object, String key) {
        JsonElement value = object.get(key);
        return value != null && value.isJsonObject() ? value.getAsJsonObject() : null;
    }

    private static JsonArray array(JsonObject object, String key) {
        JsonElement value = object.get(key);
        return value != null && value.isJsonArray() ? value.getAsJsonArray() : null;
    }

    private static boolean valid(String value) {
        return value != null && !value.trim().isEmpty();
    }

    public static final class Status {
        public final boolean forge;
        public final boolean complete;
        public final String forgeCoordinate;
        public final List<String> missingFiles;

        private Status(boolean forge, boolean complete, String forgeCoordinate, List<String> missingFiles) {
            this.forge = forge;
            this.complete = complete;
            this.forgeCoordinate = forgeCoordinate;
            this.missingFiles = missingFiles;
        }

        private static Status notForge() {
            return new Status(false, true, null, Collections.emptyList());
        }

        private IOException asException() {
            return new IOException("Forge installation is incomplete for "
                    + (forgeCoordinate == null ? "this version" : forgeCoordinate)
                    + ". Missing generated files: " + String.join(", ", missingFiles));
        }
    }
}
